# Generated by Django 3.2.6 on 2021-08-10 01:06

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(upload_to='path/media/img'),
        ),
    ]
