# Generated by Django 3.2.6 on 2021-08-10 01:14

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(upload_to='img', verbose_name='Imagem'),
        ),
    ]
