# Generated by Django 3.2.6 on 2021-08-11 22:40

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(default=1, upload_to='img', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
