# Generated by Django 3.2.6 on 2021-08-14 21:09

import ckeditor.fields
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_banner', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('sub_title_banner', models.TextField()),
                ('slug_banner', models.SlugField(max_length=255)),
                ('image_banner', stdimage.models.StdImageField(upload_to='img_banner', verbose_name='ImagemBanner')),
                ('body_banner', ckeditor.fields.RichTextField()),
                ('created_banner', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='update_cat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
