# Generated by Django 3.2.6 on 2021-08-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210814_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='update_banner',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
