# Generated by Django 3.2.6 on 2021-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_destaques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='sub_title_banner',
            field=models.TextField(max_length=151),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.TextField(max_length=151),
        ),
    ]
